networks:
  mcjava-networks:
    driver: bridge

services:
  postgres:
    image: postgres:12-alpine
    container_name: mcjava-postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - mcjava-networks